apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-u7ss
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0066-tenant/tkrw-pr712-0075-0066-app/devfile-sample-u7ss@sha256:d1b706731b9d923e1a37ba8944cec0b16ccf7faa0bcc7d4c58fc54d98ba6948c
        name: my-nodejs
        resources: {}
status: {}
